Travel/Models/TripsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using PagedList;
namespace Travel.Models
{
    public class Trips
    {
        public Route Trip { get; set; }
        public string DriverId { get; set; }
        public List<ApplicationUser> UsersList { get; set; }
    }

    public class TripsViewModel
    {
        //public List<Trips> TripsList { get; set; }
        public IPagedList<Models.Trips> TripsList { get; set; }
        public ApplicationUser User { get; set; }
    }
}

Travel/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Travel.Models;
using Microsoft.AspNet.Identity;
using PagedList;
namespace Travel.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            List<Province> provinces;
            using (ApplicationDbContext dbContext = new ApplicationDbContext())
            {
                provinces = dbContext.Provinces.ToList();
            }
            return View(provinces);
        }

        public ActionResult Trips(int id, int? page)
        {
            TripsViewModel model;
            using (ApplicationDbContext dbContext = new ApplicationDbContext())
            {
                var data = from route in dbContext.Routes where route.ProvinceId == id orderby route.RouteId select new Trips { Trip = route, DriverId= route.DriverId, UsersList = route.Users.ToList() };
                
                int pageSize = 5;
                int pageNumber = (page ?? 1);
                
                model = new TripsViewModel { TripsList = data.ToPagedList(pageNumber, pageSize), User = UserInstance(dbContext) };
            }
            ViewBag.Id = id;
            return View(model);
        }

        public ActionResult TripDetails(int id, int? page)
        {
            TravelDetailsViewModel model;
            using (ApplicationDbContext dbContext = new ApplicationDbContext())
            {
                Route route = dbContext.Routes.SingleOrDefault<Route>(a => a.RouteId == id);
                var comments = from comment in dbContext.Comments where comment.RouteId == id orderby comment.CommentId select comment;
                int pageSize = 5;
                int pageNumber = (page ?? 1);
                model = new TravelDetailsViewModel { Route = route, Users = route.Users.ToList(), DriverId = route.DriverId, User = UserInstance(dbContext), Comments= comments.ToPagedList(pageNumber,pageSize) };
            }
            ViewBag.Id = id;
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddComment(int id, string comment)
        {
            Comment commentInstance = new Comment { Body = comment, RouteId = id };
            using (ApplicationDbContext dbContext = new ApplicationDbContext())
            {
                dbContext.Comments.Add(commentInstance);
                dbContext.SaveChanges();
            }
                return RedirectToAction("TripDetails", new { id = id });
        }

        [Authorize]
        public ActionResult AddPassenger(int id)
        {
            using (ApplicationDbContext dbContext = new ApplicationDbContext())
            {
                Route route = dbContext.Routes.SingleOrDefault<Route>(a => a.RouteId == id);
                ApplicationUser user = UserInstance(dbContext);
                if(route.Users.Contains(user))
                {
                    ViewBag.Message = "Jesteś uczestnikiem poróży";
                    return View();
                }
                if (route.Users.Count >= route.MaxPassengerCount)
                {
                    ViewBag.Message = "Brak wolnych miejsc";
                    return View();
                }
                route.Users.Add(user);
                dbContext.SaveChanges();
                ViewBag.Message = "Dołączyłeś do podróży";
            }
            return View();
        }


        [Authorize]
        public ActionResult DeletePassenger(int id)
        {

            using (ApplicationDbContext dbContext = new ApplicationDbContext())
            {
                Route route = dbContext.Routes.SingleOrDefault<Route>(a => a.RouteId == id);
                route.Users.Remove(UserInstance(dbContext));
                dbContext.SaveChanges();
                ViewBag.Message = "Zrezygnowałeś z podróży";
            }

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        private ApplicationUser UserInstance(ApplicationDbContext dbContext)
        {
            string userId = User.Identity.GetUserId();
            return dbContext.Users.SingleOrDefault<ApplicationUser>(a => a.Id == userId);
        }
    }
}

Travel/Controllers/MyTripsController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Travel.Models;

namespace Travel.Controllers
{
    public class MyTripsController : Controller
    {
        // GET: MyTrips
        [Authorize]
        public ActionResult Index()
        {
            List<Route> routes;
            using (ApplicationDbContext dbContext = new ApplicationDbContext())
            {
                string userId = User.Identity.GetUserId();
                ViewBag.UserId = userId;
                routes = (from r in dbContext.Routes where r.Users.Any(u => u.Id==userId) || r.DriverId == userId  select r).ToList();
            }

            return View(routes);
        }

        public ActionResult AddTrip()
        {
            using (ApplicationDbContext dbContext = new ApplicationDbContext())
            {
                ViewBag.ProvinceId = new SelectList(dbContext.Provinces.ToList(), "ProvinceId", "Name");
            }
            return View();
        }

        [HttpPost]
        public ActionResult AddTrip(Route route)
        {
            using (ApplicationDbContext dbContext = new ApplicationDbContext())
            {
                dbContext.Routes.Add(route);
                route.DriverId = User.Identity.GetUserId();
                dbContext.SaveChanges();
            }
                return RedirectToAction("TripDetails", "Home", new { id = route.RouteId });
        }

        public ActionResult DeleteTrip(int id)
        {
            using (ApplicationDbContext dbContext = new ApplicationDbContext())
            {
                Route currentRoute = dbContext.Routes.SingleOrDefault(r => r.RouteId == id);
                if (currentRoute != null)
                {
                    currentRoute.Users.Clear();
                    dbContext.Routes.Remove(currentRoute);
                    dbContext.SaveChanges();
                }
            }
            return RedirectToAction("Index");
        }

        private ApplicationUser UserInstance(ApplicationDbContext dbContext)
        {
            string userId = User.Identity.GetUserId();
            return dbContext.Users.SingleOrDefault<ApplicationUser>(a => a.Id == userId);
        }
    }
}

Travel/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Travel/Views/Home/AddPassenger.cshtml
@{
    ViewBag.Title = "AddPassenger";
}

<h2>@ViewBag.Message</h2>

Travel/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Travel/Views/Home/DeletePassenger.cshtml
@{
    ViewBag.Title = "DeletePassenger";
}

<h2>@ViewBag.Message</h2>

Travel/Views/Home/Index.cshtml
@model IEnumerable<Travel.Models.Province>

@{
    ViewBag.Title = "Rejony";
}
<h2>Rejony </h2>

<div id="Provinces">
    
    @foreach (var province in Model)
    {
        @Html.ActionLink(province.Name, "Trips","Home",new {id = province.ProvinceId },null);
        <br/>
    }

</div>

Travel/Views/Home/TripDetails.cshtml
@model Travel.Models.TravelDetailsViewModel
@using PagedList.Mvc;
@using Travel.Models;
@{
    ViewBag.Title = "TripDetails";
}

<h2>
    Szczegóły podróży
</h2>

<ul>

    <li> Start: @Model.Route.FromName </li>
    <li> Cel: @Model.Route.ToName</li>
    <li> Data: @Model.Route.TravelDate</li>
    <li> Opis: @Model.Route.Description </li>
    <li>
        Pasażerowie:
        <ul>
            @foreach (var user in Model.Users)
            {
                <li>@user.UserName </li>
            }

        </ul>
    </li>
</ul>
@if (Model.User != null && Model.DriverId == Model.User.Id)
{
    @Html.ActionLink("Usuń podróż", "DeleteTrip", "MyTrips", new { id = Model.Route.RouteId }, null);
}
else if (Model.Route.Users.Contains(Model.User))
{
    @Html.ActionLink("Zrezygnuj z podróży", "DeletePassenger", "Home", new { id = Model.Route.RouteId }, null);
}


else if (Model.Route.Users.Count < Model.Route.MaxPassengerCount)
{
    @Html.ActionLink("Dołącz", "AddPassenger", "Home", new { id = Model.Route.RouteId }, null)
}

<h4> Komentarze</h4>
<ul>
    @foreach (Comment comment in Model.Comments)
    {
        <li>@comment.Body</li>
    }
</ul>

@if (User?.Identity.IsAuthenticated == true)
{
    using (Html.BeginForm("AddComment", "Home", new { id = Model.Route.RouteId }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <div class="col-md-10">
                    @Html.Editor("comment", new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessage("comment", "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
}
 Strona @(Model.Comments.PageCount < Model.Comments.PageNumber ? 0 : Model.Comments.PageNumber) / @Model.Comments.PageCount

@Html.PagedListPager(Model.Comments, page => Url.Action("TripDetails",
                                     new
                                     {
                                         ViewBag.Id,
                                         page
                                     }))

Travel/Views/Home/Trips.cshtml
@model Travel.Models.TripsViewModel
@using PagedList.Mvc;
@{
    ViewBag.Title = "Podróże";
}
<h2>Trasy</h2>
<div id="trips">
    @foreach (var trip in Model.TripsList)
    {
        <ul>
            <li>
                <text>Z: </text>@trip.Trip.FromName
                <br>
                <text> Do: </text> @trip.Trip.ToName
                <br>
                <text> Ilość pasażerów: </text> @trip.UsersList.Count
                <br />
                @if (Model.User != null && trip.DriverId == Model.User.Id)
                {
                    @Html.ActionLink("Usuń podróż", "DeleteTrip", "MyTrips", new { id = trip.Trip.RouteId }, null);
                }
                else if (trip.UsersList.Contains(Model.User))
                {
                    @Html.ActionLink("Zrezygnuj z podróży", "DeletePassenger", "Home", new { id = trip.Trip.RouteId }, null);
                }
                else if (trip.UsersList.Count < trip.Trip.MaxPassengerCount)
                {
                    @Html.ActionLink("Dołącz", "AddPassenger", "Home", new { id = trip.Trip.RouteId }, null);
                }
                @Html.ActionLink("Szczegóły", "TripDetails", "Home", new { id = trip.Trip.RouteId }, null)

            </li>
        </ul>
    }
    Strona @(Model.TripsList.PageCount < Model.TripsList.PageNumber ? 0 : Model.TripsList.PageNumber) / @Model.TripsList.PageCount

@Html.PagedListPager(Model.TripsList, page => Url.Action("Trips",
                    new
                    {
                        ViewBag.Id,
                        page
                    }))

</div>